import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt
from pandas.plotting import autocorrelation_plot

np.random.seed(42)
date_range = pd.date_range(start="2023-01-01", periods=100)
location_list = [
    "Downtown", "Suburb", "Industrial Area", "Residential Zone", "City Center",
    "Eastside", "Westside", "Uptown", "Rural Outskirts", "Metro Hub"
][:5]  

crime_categories = ["Assault", "Burglary", "Theft", "Vandalism", "Drug Offense"]

synthetic_records = []
for day in date_range:
    for area in location_list:
        incidents = np.random.poisson(lam=5)
        for _ in range(incidents):
            synthetic_records.append({
                "Date": day,
                "Location": area,
                "Crime_Type": np.random.choice(crime_categories),
                "Severity": np.random.choice(["Low", "Medium", "High"], p=[0.5, 0.3, 0.2])
            })

crime_df = pd.DataFrame(synthetic_records)

aggregated_data = crime_df.groupby(['Date', 'Location']).size().reset_index(name='Incident_Count')

crime_df.to_csv("synthetic_crime_dataset.csv", index=False)
print("Synthetic dataset saved as 'synthetic_crime_dataset.csv'.")

downtown_crime = aggregated_data[aggregated_data['Location'] == 'Downtown']
downtown_crime.set_index('Date', inplace=True)

downtown_series = downtown_crime['Incident_Count'].reindex(pd.date_range(start=downtown_crime.index.min(), 
                                                                         end=downtown_crime.index.max()), 
                                                           fill_value=0)

plt.figure(figsize=(10, 6))
autocorrelation_plot(downtown_series)
plt.title("Autocorrelation for Downtown Crime Incidents\nGenerated by Prithvi Kathuria (21BBS0158)")
plt.show()

model = ARIMA(downtown_series, order=(5, 1, 0))
model_fit = model.fit()

print("ARIMA Model Summary:\n")
print(model_fit.summary())

future_forecast = model_fit.forecast(steps=10)
print("\nForecast for the next 10 days:\n", future_forecast)

plt.figure(figsize=(10, 6))
plt.plot(downtown_series, label="Observed Incidents")
plt.plot(future_forecast, label="Forecasted Incidents", linestyle="--")
plt.title("Crime Incidents in Downtown: Observed vs Forecast\nGenerated by Prithvi Kathuria (21BBS0158)")
plt.legend()
plt.show()

downtown_series.to_csv("downtown_crime_series.csv", index=True)
print("Time series for 'Downtown' saved as 'downtown_crime_series.csv'.")